#!/usr/bin/env python3
"""Generate content/facts-requested.yaml (myAD Content -> myAD Research handoff).

Collects every fact id referenced by a card (fact_refs, verified_only_refs, {fact:<id>}
placeholders, paragraph_facts) or by a desk (desks.yaml fact_refs), adds the six contact
facts <desk-id>.{name,phone,url,address,hours,languages} for every desk, and writes one
entry per id. need/question/value_type/kind/topics/hint come from the hand-written
tables below; ids that hit the fallback are listed on stdout so the tables can be fixed.

Never put a value (number, phone, date, price, desk URL) into this file: the plans are
cited by file and section only.

Usage: python3 content/tools/gen_facts_requested.py [--check|--check-fresh]
  --check        only print the summary, do not write the file.
  --check-fresh  generate in memory and fail if facts-requested.yaml is stale.
"""
from __future__ import annotations

import argparse
import collections
import glob
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "content"
OUT = CONTENT / "facts-requested.yaml"
TOPICS_FILE = ROOT / "research" / "topics.yaml"

import re  # noqa: E402
PLACEHOLDER_RE = re.compile(r"\{fact:([^{}\s]+)\}")
DESK_FIELDS = ("name", "phone", "url", "address", "hours", "languages")
DESK_FIELD_TYPES = {"name": "code", "phone": "phone", "url": "code", "address": "place",
                    "hours": "text", "languages": "codes"}
VALUE_TYPES = ("text", "code", "codes", "phone", "date", "money", "quantity", "weekdays", "place", "flag")
SEED_TOPICS = ("trash", "schools", "parcel", "water", "parks", "libraries", "voting", "representatives",
               "transit", "tolls", "rent", "legal-aid", "desk", "immigration", "tps", "license", "municipality")
PLAN_REF_PLANS = ("myamericandream-plan.md", "mymiami-plan.md", "mymiami-public-data.md")

HEADER = """# Content -> Research handoff. Owner: myAD Content (writes), myAD Research (fulfils).
# One entry per fact a card needs that is not yet in research/facts/*.json.
#   - id: <pack-id>.<topic>.<field>   # the id the card uses in {fact:<id>} and fact_refs
#     card: <card id>
#     need: <what the number/phone/day/rule is, in plain words>
#     hint: <where the plans say it comes from, optional>
# Generated by content/tools/gen_facts_requested.py (do not hand-edit; fix the tables there).
# No values here: plans are cited by file and section only. Rent, income, and trash facts stay
# split by jurisdiction (us-fl-miamidade = unincorporated county / county area, us-fl-miami = City of Miami).
"""

JURIS = {"us": "United States (federal)", "us-fl": "Florida (statewide)",
         "us-fl-miamidade": "Miami-Dade County", "us-fl-miami": "City of Miami only"}

VO_HINT = ("reported by Discovery, unverified, primary source required "
           "(USCIS / Federal Register / CMS / FL AHCA)")
GROCERY_NOTE = "demo status only, visibly labelled"
BENEFITS_TAGS = {"health", "benefits"}

# --------------------------------------------------------------------------------------
# Hints: key -> (text, (plan, section) or None). Section names only; never values.
PD = "mymiami-public-data.md"
MP = "myamericandream-plan.md"
MM = "mymiami-plan.md"
ADD = "myamericandream-plan-additions.md"
WOW = "myamericandream-wow-factors.md"
SAME = "What is the same in every city, and what is Miami"
PACK = "Miami pack — endpoints that answered"
SPINE = "National spine — every city gets this for free"
CBC = "Card by card"
H = {
    "trash_city": (f"{PD} § {PACK}: City of Miami SolidWaste/TrashRoutes layer (City of Miami pins only)", (PD, PACK)),
    "trash_county": (f"{PD} § {PACK}: county CommunityServices/MD_GarbageRecycle routes (county collection area only); service-area list from the county waste service page", (PD, PACK)),
    "cart_city": (f"plans name only the pickup-day layer ({PD} § {PACK}); cart set-out rules come from the City of Miami solid-waste code or service page", (PD, PACK)),
    "cart_county": (f"plans name only the pickup-day layers ({PD} § {PACK}); cart set-out rules come from the Miami-Dade solid-waste code or service page", (PD, PACK)),
    "income_city": (f"{PD} § {SPINE}: the City of Miami income table (HTML page); {MP} § {SAME} → Money: rent line", (PD, SPINE)),
    "income_county": (f"{PD} § {SPINE}: HUD User Income Limits API for Miami-Dade; the county's own table once Research sources it (ARCHITECTURE.md 13.z jurisdiction rule)", (PD, SPINE)),
    "rent_county": (f"{PD} § {SPINE} and § {CBC}: Florida Housing rent limits as compiled by the Shimberg Center, Miami-Dade row", (PD, SPINE)),
    "wage": (f"{PD} § {CBC}: BLS occupational medians for the Miami metro against the county rent table", (PD, CBC)),
    "bls": (f"{PD} § {SPINE}: BLS Public Data API (occupational wages, Miami metro)", (PD, SPINE)),
    "buildings": (f"{PD} § {CBC}: FloridaHousingSearch.org listings (public site, no public API)", (PD, CBC)),
    "hud": (f"{PD} § {SPINE}: HUD User Income Limits (what the bands are for)", (PD, SPINE)),
    "parcel": (f"{PD} § {PACK}: MD_LandInformation layer 26 Parcels (folio, year built, condo flag, use)", (PD, PACK)),
    "condo_listings": (f"{MP} § {SAME} → The hard papers: condo assessment share of listings (listing-data source not named; Research to find it)", (MP, SAME)),
    "condo_law": ("not named in the plans; Florida condominium statute and DBPR condominium division (milestone inspections, reserve studies)", None),
    "gmx": (f"{PD} § Tolls, as a file the app can trust: GMX toll rate schedule PDF (2-axle rows)", (PD, "Tolls, as a file the app can trust")),
    "toll_rules": (f"{MP} § {SAME} → Money: the toll bill (agency, sticker not on the account, express lanes); {PD} § Tolls, as a file the app can trust", (MP, SAME)),
    "muni": (f"{PD} § {PACK}: MD_MDPDViewer layer 8 Municipality polygons", (PD, PACK)),
    "census": (f"{PD} § {SPINE}: Census geocoder (incorporated place or county subdivision)", (PD, SPINE)),
    "grocery": (f"{MM} § Money and {PD} § {CBC}: no public shelf-price source; {GROCERY_NOTE}", (MM, "Money")),
    "places": (f"{PD} § {PACK}: MD_RecreationCulture (parks), MD_Libraries, MD_PublicSafety (fire stations, police grid)", (PD, PACK)),
    "power": (f"{MP} § {SAME} → Money: power range labelled as neighbor reports from Kendall, not this meter", (MP, SAME)),
    "school": (f"{PD} § {PACK}: CommunityServices/MD_Educational layers 9 elementary, 10 high, 11 middle (phone, grades, address on the feature)", (PD, PACK)),
    "busrule": (f"{PD} § {CBC}: the school-bus distance rule, computed parcel to school point", (PD, CBC)),
    "mdcps": (f"{ADD} § 9. School enrollment packet; {MP} § {SAME} → Movement and morning: school run (magnet means the parent drives)", (MP, SAME)),
    "buscam": (f"{PD} § {CBC} → Rules: school-bus camera tickets (county suspended some tickets)", (PD, CBC)),
    "tow": (f"{PD} § {CBC} → Rules: tow letter vs county citation, county basic-tow cap cited by residents (Research must source the county ordinance)", (PD, CBC)),
    "transit": (f"{PD} § {PACK}: county GTFS zip (routes, stops, stop times, fares); realtime feeds listed but unverified", (PD, PACK)),
    "sfrta": ("not named in the plans; SFRTA's own fare-change public-hearing notice and Tri-Rail fares page (Tri-Rail is run by SFRTA, not by the county transit department)", None),
    "mia": (f"{WOW} § 11. Arrival Relay (MIA ground transport, airport solicitation, Metrorail to MIA)", None),
    "water": (f"{PD} § {PACK}: CommunityServices/MD_WaterSewer layers 0 sewer, 1 water", (PD, PACK)),
    "vote": (f"{PD} § {PACK}: MD_KnowWhereToVote (polling place, early voting, commission, Congress, state senate and house)", (PD, PACK)),
    "broadband": (f"{PD} § {PACK}: MD_RecreationCulture layer 4 MDBroadbandProvider", (PD, PACK)),
    "311": (f"{PD} § {PACK}: 311 history feature services (the county marks them beta); § {CBC}: filing is the county portal and the 311 Direct app", (PD, PACK)),
    "311_city": (f"{MP} § {SAME} → Errands: 311 in the right city, in the right language (City of Miami line not named)", (MP, SAME)),
    "ped": (f"{MM} § Getting around and the school morning; {PD} § {CBC}: FLHSMV quarterly crash aggregates", (MM, "Getting around and the school morning")),
    "str": (f"{MP} § {SAME} → The hard papers: short stays eating long-term rentals (source not named)", (MP, SAME)),
    "taxcoll": (f"{PD} § {CBC}: license and tag appointments are the Miami-Dade Tax Collector calendar; {MP} § {SAME} → Errands: FLOW at the library", (PD, CBC)),
    "flhsmv": (f"{ADD} § 3. Is my license good here?; {MP} § The first month, once they are sleeping (document buckets); FLHSMV document pages", (MP, "The first month, once they are sleeping")),
    "eviction": (f"{MP} § {SAME} → The hard papers: eviction clock; {MM} § Housing traps and the bad week (Florida landlord-tenant statute)", (MM, "Housing traps and the bad week")),
    "origin": (f"{MP} § Origin lens (driving ethics, bribery, right on red, school bus); FLHSMV driver handbook", (MP, "Origin lens")),
    "insurance": (f"{MP} § Origin lens (driving ethics); Florida DHSMV insurance requirement pages (not named in the plans)", (MP, "Origin lens")),
    "country": (f"{MP} § {SAME} → The country, same everywhere", (MP, SAME)),
    "rights": (f"{MP} § {SAME} → The country: 911 and the police-stop script", (MP, SAME)),
    "status": (f"{MP} § {SAME} → The country: status words, only an accredited representative or a lawyer advises", (MP, SAME)),
    "helper": (f"{ADD} § 5. Helper check (EOIR recognized organizations and accredited representatives, notario warning)", None),
    "paper": (f"{ADD} § 1. Paper clock and § 3. Moving-day paper chain (USCIS and SEVIS address and notice rules)", None),
    "f1": (f"{ADD} § 1. Paper clock (F-1, DSO, SEVIS); {MP} § Who it is for", (MP, "Who it is for")),
    "remit": (f"{ADD} § 5. Sending money home (CFPB remittance rule)", None),
    "bank": (f"{ADD} § 4. Safe first account; {MP} § {SAME} → The country: banks, credit, remittance", (MP, SAME)),
    "hospital": (f"{ADD} § 2. Hospital form question (EMTALA); {MP} § {SAME} → Health: ER versus clinic", (MP, SAME)),
    "schoolenr": (f"{ADD} § 9. School enrollment packet (immunization form, enrollment documents)", None),
    "heat": (f"{ADD} § 9. Heat and water day", None),
    "pay": (f"{ADD} § 6. Pay check; {MP} § {SAME} → The country: tipping", (MP, SAME)),
    "citizen": (f"{ADD} § 7. Citizen-only boxes", None),
    "coverage": (f"{ADD} § Batch 2, 1. Coverage change check (ACCESS Florida / DCF desk)", None),
    "cred": (f"{ADD} § 12. Your profession here (credential evaluation)", None),
    "taxes": (f"{MP} § {SAME} → The country: Social Security, ITIN, taxes (IRS and SSA pages not named)", (MP, SAME)),
    "medbill": (f"{MP} § {SAME} → The hard papers: a medical bill, what to ask (hospital financial-assistance policy not named)", (MP, SAME)),
    "help": (f"{MP} § {SAME} → The hard papers: help this week (211, clinic, shelter intake)", (MP, SAME)),
    "lease": (f"{MP} § {SAME} → The country: lease patterns (application fee, wire-before-visit, income multiple)", (MP, SAME)),
    "letter": (f"{ADD} § 2. Letter & text reader (FTC impostor and toll-text scams)", None),
    "fema": (f"{ADD} § Batch 3b: FEMA flood-zone lookup for the address pin", None),
    "business_tax": (f"{ADD} § Batch 4: Florida local business tax receipts and Miami-Dade renewal rules", None),
}

EP = {
    "trash_city": "gis.miami.gov SolidWaste/TrashRoutes MapServer layer 0 (TRASHDAY)",
    "garbage": "CommunityServices/MD_GarbageRecycle MapServer layer 1 GarbagePickupRoute (WEEKDAYS)",
    "recycling": "CommunityServices/MD_GarbageRecycle MapServer layer 2 RecyclingRoute (WEEKDAY, PICKUPWEEK)",
    "parcel": "MD_LandInformation MapServer layer 26 Parcels",
    "muni": "MD_MDPDViewer MapServer layer 8 Municipality (NAME, MUNICID)",
    "school_e": "CommunityServices/MD_Educational MapServer layer 9 (elementary attendance boundary)",
    "school_m": "CommunityServices/MD_Educational MapServer layer 11 (middle attendance boundary)",
    "school_h": "CommunityServices/MD_Educational MapServer layer 10 (high attendance boundary)",
    "vote": "MD_KnowWhereToVote MapServer",
    "water": "CommunityServices/MD_WaterSewer MapServer layer 1 (water)",
    "sewer": "CommunityServices/MD_WaterSewer MapServer layer 0 (sewer)",
    "parks": "CommunityServices/MD_RecreationCulture MapServer layers 0 municipal parks, 1 county parks",
    "library": "MD_Libraries MapServer",
    "safety": "CommunityServices/MD_PublicSafety MapServer (stations, police grid)",
    "broadband": "CommunityServices/MD_RecreationCulture MapServer layer 4 MDBroadbandProvider",
    "311": "services.arcgis.com data_311_* feature services (beta)",
    "gtfs": "Miami-Dade Transit GTFS zip (Mobility Database mdb-331)",
    "census": "Census geocoder (geocoding.geo.census.gov), county subdivision layer",
    "fema": "FEMA National Flood Hazard Layer / NFIP Map Service Center",
}

# --------------------------------------------------------------------------------------
# Per-id table (hand-written). S = static, L = lookup (address- or household-dependent).
MD, MI, FL, US = "us-fl-miamidade", "us-fl-miami", "us-fl", "us"


def S(need, vt, topics, hint, pub, **kw):
    return dict(need=need, vt=vt, kind="static", topics=topics, hint=hint, pub=pub, **kw)


def L(need, vt, topics, hint, pub, q, endpoint=None, **kw):
    return dict(need=need, vt=vt, kind="lookup", topics=topics, hint=hint, pub=pub, q=q, endpoint=endpoint, **kw)


CITY_HCD = "City of Miami (Department of Housing and Community Development)"
CITY_SW = "City of Miami (Solid Waste Department)"
MD_PHCD = "Miami-Dade County (Public Housing and Community Development)"
MD_SW = "Miami-Dade County (Solid Waste Management)"
MD_GIS = "Miami-Dade County GIS"
MD_PA = "Miami-Dade Property Appraiser (county GIS)"
MDCPS = "Miami-Dade County Public Schools"
MDCPS_GIS = "Miami-Dade County Public Schools (county GIS)"
ELECT = "Miami-Dade Elections (county GIS)"
DTPW = "Miami-Dade Department of Transportation and Public Works"
MIA = "Miami International Airport (Miami-Dade Aviation Department)"
GMX = "Greater Miami Expressway Agency"
FEMA = "Federal Emergency Management Agency (FEMA)"
CMS = "Centers for Medicare & Medicaid Services (CMS)"
FPL = "Florida Power & Light"
LIHEAP = "Miami-Dade County Community Action and Human Services / LIHEAP"

F: dict[str, dict] = {
    # ---- City of Miami (us-fl-miami): kept separate from the county on purpose
    f"{MI}.311.phone": S("City of Miami's own service-request (311) phone line, used only for pins inside the City of Miami", "phone", ["municipality", "desk"], "311_city", "City of Miami"),
    f"{MI}.housing.household-vs-limit": L("City of Miami only: whether this household's size and income fall under the city's own income table, and at which percent band", "text", ["rent", "municipality"], "income_city", CITY_HCD,
        "For a household inside the City of Miami (size and yearly income from the household), which band of the City of Miami income table does it fall in, if any?"),
    f"{MI}.housing.income-limit-1p-50": S("City of Miami only: yearly income limit for a one-person household at 50 percent of area median income, from the city's current income table", "money", ["rent", "municipality"], "income_city", CITY_HCD, unit="USD"),
    f"{MI}.housing.income-limit-4p-50": S("City of Miami only: yearly income limit for a four-person household at 50 percent of area median income, from the city's current income table", "money", ["rent", "municipality"], "income_city", CITY_HCD, unit="USD"),
    f"{MI}.trash.cart-rules": S("City of Miami only: when carts may go to the curb and must come back, and where they sit", "text", ["trash", "municipality"], "cart_city", CITY_SW),
    f"{MI}.trash.city-hauls": S("City of Miami only: the rule that the city collects its own household trash, so the county's pickup map does not cover city pins", "text", ["trash", "municipality"], "trash_city", CITY_SW),
    f"{MI}.trash.day": L("City of Miami only: the weekday(s) household trash is picked up at this pin", "weekdays", ["trash", "municipality"], "trash_city", CITY_SW,
        "For a pin inside the City of Miami, which weekday(s) does the city collect household trash (TrashRoutes TRASHDAY)?", EP["trash_city"]),
    # ---- Miami-Dade County (us-fl-miamidade): county-wide or unincorporated
    f"{MD}.broadband.providers-on-block": L("Internet providers that advertise service on the pin's census block, with technology and advertised top speed", "codes", [], "broadband", MD_GIS,
        "For a pin, which providers advertise broadband on its census block, and what technology and max down/up speed does each list?", EP["broadband"]),
    f"{MD}.condo.listings-with-assessment": S("Share of active Miami condo listings that declare a special assessment", "quantity", ["parcel"], "condo_listings", "to be identified by Research (listing-data publisher)", unit="percent", ftype="practice"),
    f"{MD}.gov.municipality": L("The municipality (city, town, or village) the pin sits in, or that it is in unincorporated Miami-Dade", "code", ["municipality"], "muni", MD_GIS,
        "For a pin, which municipality polygon contains it (official NAME), or does none (unincorporated Miami-Dade)?", EP["muni"]),
    f"{MD}.gov.unincorporated": L("Whether the pin is in unincorporated Miami-Dade, where the county itself is the local government", "flag", ["municipality"], "muni", MD_GIS,
        "For a pin, is it outside every municipality polygon (unincorporated Miami-Dade)?", EP["muni"]),
    f"{MD}.groceries.demo-basket": S("Price of a fixed demo grocery basket at named Miami stores; demo status only, visibly labelled, never shown as a real price", "money", [], "grocery", "myAD demo data (no public shelf-price source)", unit="USD", ftype="demo", note=GROCERY_NOTE),
    f"{MD}.housing.household-vs-limit": L("Unincorporated Miami-Dade (county table): whether this household's size and income fall under Miami-Dade County's own income limits, and at which band", "text", ["rent"], "income_county", MD_PHCD,
        "For a household in unincorporated Miami-Dade (size and yearly income from the household), which band of Miami-Dade County's own income-limit table does it fall in, if any?"),
    f"{MD}.housing.income-limits": S("Unincorporated Miami-Dade (county table): that Miami-Dade County publishes its own income limits by household size and percent of area median income, and which table is current", "text", ["rent"], "income_county", MD_PHCD),
    f"{MD}.housing.matching-buildings": L("Affordable buildings in Miami-Dade whose income rules this household meets, each with its phone (a list to call, not a vacancy)", "codes", ["rent"], "buildings", "Florida Housing Finance Corporation (FloridaHousingSearch.org)",
        "For this household's size and income, which listed affordable buildings in Miami-Dade accept it, with name and phone for each?"),
    f"{MD}.housing.rent-limit-2br-60": S("Unincorporated Miami-Dade (county row): program rent limit for a two-bedroom unit at 60 percent of area median income", "money", ["rent"], "rent_county", "Florida Housing Finance Corporation / Shimberg Center (Miami-Dade County row)", unit="USD"),
    f"{MD}.housing.wage-vs-rent": L("How the Miami-metro median wage for the household's job compares with the county program rent limit (for example, share of monthly pay)", "text", ["rent"], "wage", "BLS OEWS and Florida Housing / Shimberg Center",
        "For the household's occupation, how does the Miami-metro median wage compare with Miami-Dade County's two-bedroom program rent limit?"),
    f"{MD}.m-dcps.bus-distance": S("Distance from home to school inside which Miami-Dade public schools do not owe the student a bus", "quantity", ["schools", "transit"], "busrule", f"{MDCPS} (Transportation)", unit="mile"),
    f"{MD}.m-dcps.choice-transport": S("Rule that magnet and choice-school students usually get no district bus, so the parent drives", "text", ["schools", "transit"], "mdcps", MDCPS),
    f"{MD}.m-dcps.enrollment-documents": S("Documents Miami-Dade public schools ask for at enrollment (proof of address, age, immunization and health forms)", "text", ["schools"], "mdcps", MDCPS),
    f"{FL}.fac.6a-6.0908.parent-communication": S("Florida rule requiring school-district communication with current or former English Language Learners' parents in their primary language or commonly used mode, unless clearly not feasible", "text", ["schools", "language"], "mdcps", MDCPS),
    f"{MD}.m-dcps.policy-2111": S("M-DCPS policy commitment to communicate with parents in their primary language and adjust the communication mode when needed", "text", ["schools", "language"], "mdcps", MDCPS),
    f"{US}.ecfr.34-300.322e.iep-interpreter": S("Federal rule requiring the school to arrange an interpreter when needed for a parent to understand an IEP Team meeting", "text", ["schools", "language"], "mdcps", "ECFR"),
    f"{MD}.m-dcps.bilingual-education.phone": S("Public phone number for the M-DCPS Department of Bilingual Education and World Languages", "phone", ["schools", "language", "desk"], "mdcps", MDCPS),
    f"{MD}.m-dcps.parent-portal-bus-stop": S("Where a parent finds the assigned bus stop and pickup time (district parent portal)", "text", ["schools", "transit"], "mdcps", MDCPS),
    f"{MD}.m-dcps.meals.full-price-from": S("Date Miami-Dade public schools began charging the full-price meal amount", "date", ["schools"], "schoolenr", MDCPS),
    f"{MD}.m-dcps.meals.cep-school-count": S("Number of Miami-Dade public schools participating in the Community Eligibility Provision", "quantity", ["schools"], "schoolenr", MDCPS, unit="school"),
    f"{MD}.m-dcps.meals.full-price-lunch": S("Full-price lunch amount in Miami-Dade public schools", "money", ["schools"], "schoolenr", MDCPS, unit="USD"),
    f"{MD}.m-dcps.meals.form-no-ssn-ok": S("Whether the Miami-Dade school-meal form may be submitted without a Social Security number", "flag", ["schools"], "schoolenr", MDCPS),
    f"{MD}.mia.ground-transport": S("Official ground-transport options from Miami International Airport and where each one leaves from", "text", ["transit"], "mia", MIA),
    f"{MD}.mia.taxi.meter-rule": S("Current metered taxi fare rule for trips from Miami International Airport", "text", ["transit", "visitors"], "mia", MIA),
    f"{MD}.mia.taxi.flat-rate-rule": S("Miami-Dade rule that MIA taxi trips are metered and flat fares are eliminated", "text", ["transit", "visitors"], "mia", MIA),
    f"{MD}.mia.solicitation": S("Airport rule against unlicensed ride and hotel solicitation at MIA, and what to use instead", "text", ["transit"], "mia", MIA),
    f"{MD}.parcel.condo-flag": L("Whether the pin's parcel is recorded as a condominium", "flag", ["parcel"], "parcel", MD_PA, "For a pin, is the parcel (buffered point) flagged as a condominium?", EP["parcel"]),
    f"{MD}.parcel.folio": L("The parcel's folio number (the county's id for the property)", "code", ["parcel"], "parcel", MD_PA, "For a pin, what folio does the containing parcel carry?", EP["parcel"]),
    f"{MD}.parcel.use": L("The parcel's land-use description as the county records it", "text", ["parcel"], "parcel", MD_PA, "For a pin, what use description does the parcel carry, in the county's own wording?", EP["parcel"]),
    f"{MD}.parcel.year-built": L("Year the building on the parcel was built", "quantity", ["parcel"], "parcel", MD_PA, "For a pin, what year built does the parcel record?", EP["parcel"], unit="year"),
    f"{MD}.pedestrian.hit-latest-year": S("Number of pedestrians hit by vehicles in Miami-Dade in the latest full year published", "quantity", ["transit"], "ped", "Florida DHSMV (crash data)", unit="person"),
    f"{MD}.pedestrian.killed-latest-year": S("Number of pedestrians killed by vehicles in Miami-Dade in the latest full year published", "quantity", ["transit"], "ped", "Florida DHSMV (crash data)", unit="person"),
    f"{MD}.pedestrian.state-rank": S("Where Miami-Dade (or the Miami metro) ranks for pedestrian danger in a named published ranking", "quantity", ["transit"], "ped", "to be identified by Research (FDOT / Smart Growth America)", unit="rank"),
    f"{MD}.places.grocery-stores": L("Grocery stores near the pin, by name", "codes", [], "grocery", "to be identified by Research (places data)", "For a pin, which grocery stores lie within a short distance, by name?"),
    f"{MD}.places.nearest-fire-station": L("The fire station nearest the pin", "place", [], "places", MD_GIS, "For a pin, which fire station is nearest (name, address, location)?", EP["safety"]),
    f"{MD}.places.nearest-library": L("The public library branch nearest the pin (county or municipal)", "place", ["libraries"], "places", MD_GIS, "For a pin, which library branch is nearest (name, address, location)?", EP["library"]),
    f"{MD}.places.nearest-park": L("The public park nearest the pin (county or municipal)", "place", ["parks"], "places", MD_GIS, "For a pin, which park is nearest (name, address, location)?", EP["parks"]),
    f"{MD}.power.neighbor-reports-kendall": S("Range of summer power bills neighbors in Kendall report, labelled as neighbor reports and not this meter", "text", [], "power", "neighbor reports (Kendall)", ftype="neighbor-report"),
    f"{MD}.safety.police-agency": L("Which police agency serves the pin (city police or the county sheriff's office)", "code", ["municipality"], "places", MD_GIS, "For a pin, which police agency's district or grid contains it?", EP["safety"]),
    f"{MD}.school-bus-camera.contest-process": S("How to contest a Miami-Dade school-bus camera ticket, and the deadline rule for doing it", "text", ["schools"], "buscam", f"Miami-Dade County / {MDCPS}"),
    f"{MD}.school-bus-camera.suspensions": S("That the county suspended or voided some school-bus camera tickets, and which ones", "text", ["schools"], "buscam", "Miami-Dade County"),
    f"{MD}.school.distance-to-zoned": L("Distance from the pin to its zoned elementary school", "quantity", ["schools"], "busrule", "Miami-Dade County GIS (computed)", "For a pin, how far is it from the parcel to the zoned elementary school point on the same layer?", EP["school_e"], unit="mile"),
    f"{MD}.school.zoned-elementary": L("The elementary school the pin is zoned for", "place", ["schools"], "school", MDCPS_GIS, "For a pin, which elementary attendance boundary contains it (school name and location)?", EP["school_e"]),
    f"{MD}.school.zoned-elementary-address": L("Street address of the zoned elementary school", "place", ["schools"], "school", MDCPS_GIS, "For a pin, what address does the zoned elementary school's feature carry?", EP["school_e"]),
    f"{MD}.school.zoned-elementary-grades": L("Grade span the zoned elementary school serves", "code", ["schools"], "school", MDCPS_GIS, "For a pin, what grade span does the zoned elementary school's feature carry?", EP["school_e"]),
    f"{MD}.school.zoned-elementary-phone": L("Front-office phone of the zoned elementary school", "phone", ["schools"], "school", MDCPS_GIS, "For a pin, what phone does the zoned elementary school's feature carry?", EP["school_e"]),
    f"{MD}.school.zoned-high": L("The high school the pin is zoned for", "place", ["schools"], "school", MDCPS_GIS, "For a pin, which high-school attendance boundary contains it (school name and location)?", EP["school_h"]),
    f"{MD}.school.zoned-middle": L("The middle school the pin is zoned for", "place", ["schools"], "school", MDCPS_GIS, "For a pin, which middle-school attendance boundary contains it (school name and location)?", EP["school_m"]),
    f"{MD}.short-term-rentals.rules": S("Miami-Dade rules for short-term (vacation) rentals: registration, where they are allowed, and how to report one", "text", ["rent"], "str", "Miami-Dade County"),
    f"{MD}.towing.private-vs-citation": S("Difference between a private towing company's demand letter and a county or city citation", "text", [], "tow", "Miami-Dade County (Consumer Protection)"),
    f"{MD}.towing.rate-cap": S("Maximum rate the county allows for a basic non-consent tow", "money", [], "tow", "Miami-Dade County (Consumer Protection, towing rates)", unit="USD"),
    f"{MD}.towing.resident-stories": S("Tow bill amounts residents report paying, labelled as neighbor reports", "money", [], "tow", "neighbor reports", unit="USD", ftype="neighbor-report"),
    f"{MD}.transit.fare.metrobus": S("Regular adult Metrobus fare", "money", ["transit"], "transit", DTPW, unit="USD"),
    f"{MD}.transit.fare.metrorail": S("Regular adult Metrorail fare", "money", ["transit"], "transit", DTPW, unit="USD"),
    f"{MD}.transit.fare.discounted": S("Discounted Miami-Dade Transit fare for eligible riders", "money", ["transit"], "transit", DTPW, unit="USD"),
    f"{MD}.transit.transfer.free-with-easy-only": S("Whether a transfer is free only when paid with an EASY Card", "text", ["transit"], "transit", DTPW),
    f"{MD}.transit.pass.monthly": S("Miami-Dade Transit regular monthly pass price", "money", ["transit"], "transit", DTPW, unit="USD"),
    f"{MD}.transit.pass.college-monthly": S("Miami-Dade Transit college monthly pass price", "money", ["transit"], "transit", DTPW, unit="USD"),
    f"{MD}.transit.metrorail-airport": S("How to reach Miami International Airport by Metrorail (line and station)", "text", ["transit"], "mia", DTPW),
    f"{MD}.transit.nearest-stop": L("The transit stop nearest the pin", "place", ["transit"], "transit", "Miami-Dade Transit (GTFS)", "For a pin, which GTFS stop is nearest (name and location)?", EP["gtfs"]),
    f"{MD}.transit.realtime": S("Whether the county's live bus and train position feed is available, or only the schedule", "text", ["transit"], "transit", DTPW),
    f"{MD}.transit.route-for-commute": L("Transit route(s) and ride length for the household's commute", "codes", ["transit"], "transit", "Miami-Dade Transit (GTFS)", "For the household's home pin and work pin, which GTFS routes connect them and how long is the ride?", EP["gtfs"]),
    f"{MD}.gmx.tolls-on-route": L("Tolls on the household's driving commute (GMX gantries crossed, SunPass and by-plate)", "money", ["tolls"], "gmx", GMX, "For the household's home and work pins, which GMX gantries does the driving route cross, and what does each cost with SunPass and by plate?", unit="USD"),
    f"{MD}.gmx.plate-vs-sunpass": S("How the toll-by-plate price compares with the SunPass price on the county expressways (the rule, for example a multiple)", "text", ["tolls"], "gmx", GMX),
    f"{MD}.trash.cart-rules": S("County collection area (unincorporated Miami-Dade and contract cities): when carts may go to the curb and must come back, and where they sit", "text", ["trash"], "cart_county", MD_SW),
    f"{MD}.trash.garbage-days": L("County collection area only (unincorporated Miami-Dade and contract cities): the weekday(s) garbage is picked up at this pin", "weekdays", ["trash"], "trash_county", MD_SW, "For a pin in the county collection area, which weekdays does GarbagePickupRoute list?", EP["garbage"]),
    f"{MD}.trash.recycling-day": L("County collection area only: the weekday recycling is picked up at this pin", "weekdays", ["trash"], "trash_county", MD_SW, "For a pin in the county collection area, which weekday does RecyclingRoute list?", EP["recycling"]),
    f"{MD}.trash.recycling-week": L("County collection area only: which alternating week code recycling is picked up at this pin", "code", ["trash"], "trash_county", MD_SW, "For a pin in the county collection area, which PICKUPWEEK does RecyclingRoute list?", EP["recycling"]),
    f"{MD}.trash.service-area": L("Whether the pin is inside the county's own trash collection area (unincorporated Miami-Dade plus the contract cities) rather than a city that hauls its own", "flag", ["trash", "municipality"], "trash_county", MD_SW,
        "For a pin, is it inside the county solid-waste collection area (unincorporated or a contract city), and if not, which municipality hauls?", EP["garbage"]),
    f"{MD}.utility.layer-updated": S("When the county last updated the water and sewer utility map layer", "date", ["water"], "water", MD_GIS),
    f"{MD}.utility.sewer-provider": L("The sewer utility that serves the pin", "code", ["water"], "water", MD_GIS, "For a pin, which sewer utility polygon contains it (utility name)?", EP["sewer"]),
    f"{MD}.utility.water-provider": L("The water utility that serves the pin", "code", ["water"], "water", MD_GIS, "For a pin, which water utility polygon contains it (utility name)?", EP["water"]),
    f"{MD}.vote.commission-district": L("The Miami-Dade County Commission district the pin is in", "code", ["representatives", "voting"], "vote", ELECT, "For a pin, which county commission district contains it?", EP["vote"]),
    f"{MD}.vote.congress-district": L("The U.S. congressional district the pin is in", "code", ["representatives", "voting"], "vote", ELECT, "For a pin, which congressional district contains it?", EP["vote"]),
    f"{MD}.vote.early-voting": L("Early-voting site nearest the pin", "place", ["voting"], "vote", ELECT, "For a pin, which early-voting site is nearest (name, address)?", EP["vote"]),
    f"{MD}.vote.polling-place": L("Election-day polling place for the pin's precinct", "place", ["voting"], "vote", ELECT, "For a pin, which precinct contains it and what is that precinct's polling place (name, address)?", EP["vote"]),
    f"{MD}.vote.state-house-district": L("The Florida House district the pin is in", "code", ["representatives", "voting"], "vote", ELECT, "For a pin, which Florida House district contains it?", EP["vote"]),
    f"{MD}.vote.state-senate-district": L("The Florida Senate district the pin is in", "code", ["representatives", "voting"], "vote", ELECT, "For a pin, which Florida Senate district contains it?", EP["vote"]),
    # desk-namespaced card facts (not contact fields)
    f"{MD}.311.filing-channels": S("Ways to file a Miami-Dade 311 request (phone, online portal, the 311 Direct app)", "text", ["desk"], "311", "Miami-Dade County 311"),
    f"{MD}.311.history-beta": S("That the county marks its 311 request-history data as beta, and that most city-only work is missing from it", "text", ["desk"], "311", "Miami-Dade County (open data)"),
    f"{MD}.311.history-near-pin": L("Count of past 311 requests near the pin, by type, from the county history data", "quantity", ["desk"], "311", "Miami-Dade County (open data)",
        "For a pin, how many 311 requests of each type were logged within a short radius in the latest year of history data?", EP["311"], unit="request"),
    f"{MD}.jackson.financial-assistance.sliding-scale-max-fpl": S("Maximum federal-poverty-guideline percentage for Jackson Health financial assistance", "quantity", ["health"], "medbill", "Jackson Health System", unit="percent"),
    f"{MD}.jackson.prime-renewal-online-only": S("Whether Jackson Prime renewal is online only", "flag", ["health"], "medbill", "Jackson Health System"),
    f"{MD}.tax-collector.flow": S("What FLOW (the Tax Collector's service at the library) offers and how to use it", "text", ["license", "libraries"], "taxcoll", "Miami-Dade Tax Collector"),
    f"{MD}.tax-collector.license-appointments": S("That driver-license and tag appointments in Miami-Dade are booked on the Tax Collector's calendar, and how", "text", ["license"], "taxcoll", "Miami-Dade Tax Collector"),
}

GANTRIES = {"sr112-32nd": "SR 112 (Airport Expressway) at 32nd Ave", "sr836-137th": "SR 836 (Dolphin Expressway) at 137th Ave",
            "sr836-97th": "SR 836 (Dolphin Expressway) at 97th Ave", "sr924-57th": "SR 924 (Gratigny Parkway) at 57th Ave"}
for g, label in GANTRIES.items():
    F[f"{MD}.gmx.{g}.name"] = S(f"Official gantry or toll-point name, as the GMX schedule writes it, for {label}", "code", ["tolls"], "gmx", GMX)
    F[f"{MD}.gmx.{g}.sunpass"] = S(f"2-axle SunPass (transponder) toll at the {label} gantry, from the current GMX schedule", "money", ["tolls"], "gmx", GMX, unit="USD")
    F[f"{MD}.gmx.{g}.plate"] = S(f"2-axle toll-by-plate toll at the {label} gantry, from the current GMX schedule", "money", ["tolls"], "gmx", GMX, unit="USD")

DHSMV = "Florida DHSMV"
FLSTAT = "Florida Statutes (landlord-tenant)"
SEVP = "U.S. ICE (SEVP) / Study in the States"
F.update({
    # ---- Florida (us-fl)
    f"{FL}.bribery.crime": S("Rule that offering money or a gift to a police officer or official is a crime in Florida", "text", [], "origin", "Florida Statutes"),
    f"{FL}.sfrta.monthly-pass.pre-increase": S("Tri-Rail regional monthly pass price before SFRTA's fare change", "money", ["transit"], "sfrta", "South Florida Regional Transportation Authority (SFRTA)", unit="USD", desk="us-fl.sfrta"),
    f"{FL}.sfrta.monthly-pass": S("Tri-Rail regional monthly pass price under SFRTA's fare change", "money", ["transit"], "sfrta", "South Florida Regional Transportation Authority (SFRTA)", unit="USD", desk="us-fl.sfrta"),
    f"{FL}.condo.milestone-inspection-age": S("Building age at which Florida requires a condo milestone safety inspection (and the coastal rule if different)", "quantity", ["parcel"], "condo_law", "Florida Statutes / DBPR", unit="year"),
    f"{FL}.condo.reserve-study": S("Florida's structural integrity reserve study requirement for condo associations, and what it can mean for owners", "text", ["parcel"], "condo_law", "Florida Statutes / DBPR"),
    f"{FL}.driving.insurance-before-registration": S("Florida rule that car insurance must be bought before a car can be registered or plated", "text", ["license"], "insurance", DHSMV),
    f"{FL}.driving.pip-minimum": S("Florida minimum personal-injury-protection coverage", "money", ["license"], "insurance", DHSMV, unit="USD"),
    f"{FL}.driving.pdl-minimum": S("Florida minimum property-damage-liability coverage", "money", ["license"], "insurance", DHSMV, unit="USD"),
    f"{FL}.driving.newcomer-registration-days": S("Number of days a Florida newcomer has to register a vehicle", "quantity", ["license"], "insurance", DHSMV, unit="day"),
    f"{FL}.driving.all-way-stop": S("Florida rule for who goes first at an all-way stop", "text", ["license"], "origin", f"{DHSMV} (driver handbook)"),
    f"{FL}.driving.dui-crime": S("That driving under the influence is a crime in Florida, with the blood-alcohol rule", "text", ["license"], "origin", f"{DHSMV} / Florida Statutes"),
    f"{FL}.driving.keep-right": S("Florida rule to keep right except to pass (left lane for passing)", "text", ["license"], "origin", f"{DHSMV} / Florida Statutes"),
    f"{FL}.driving.no-license-offense": S("What driving without a valid license is in Florida (offense level and what can happen)", "text", ["license"], "origin", "Florida Statutes"),
    f"{FL}.driving.right-on-red": S("Florida rule on turning right on red after a full stop unless a sign forbids it", "text", ["license"], "origin", f"{DHSMV} (driver handbook)"),
    f"{FL}.driving.school-bus-stop": S("Florida rule for stopping for a school bus with its stop arm out, including on divided roads", "text", ["license", "schools"], "origin", f"{DHSMV} (driver handbook)"),
    f"{FL}.driving.show-documents": S("Documents a Florida driver must show when stopped (license, registration, proof of insurance)", "text", ["license"], "rights", f"Florida Statutes / {DHSMV}"),
    f"{FL}.eviction.rent-demand-days": S("Number of days in Florida's written demand to pay rent or leave", "quantity", ["rent"], "eviction", FLSTAT, unit="day"),
    f"{FL}.eviction.notice-delivery-not-waivable": S("Florida rule that eviction-notice delivery requirements cannot be waived in a lease", "text", ["rent"], "eviction", FLSTAT),
    f"{FL}.eviction.court-registry-days": S("Number of days a Florida tenant has to pay claimed rent into the court registry", "quantity", ["rent"], "eviction", FLSTAT, unit="day"),
    f"{FL}.eviction.answer-period": S("How long a Florida tenant has to answer an eviction lawsuit after being served, and which days are counted", "quantity", ["rent"], "eviction", FLSTAT, unit="day"),
    f"{FL}.eviction.court-only": S("Rule that in Florida only a court, through the sheriff, can remove a tenant", "text", ["rent"], "eviction", FLSTAT),
    f"{FL}.eviction.default": S("What happens if a tenant does not answer an eviction suit in time (default judgment)", "text", ["rent"], "eviction", FLSTAT),
    f"{FL}.eviction.no-self-help": S("Rule that a Florida landlord may not change locks, cut utilities, or remove belongings to force a tenant out", "text", ["rent"], "eviction", FLSTAT),
    # Deposit facts are Florida landlord-tenant rules; the lease card ends at the existing local legal-aid desk.
    f"{FL}.landlord.deposit.return-days-no-claim": S("Number of days for a Florida landlord to return a deposit when there is no claim", "quantity", ["rent"], "lease", FLSTAT, unit="day"),
    f"{FL}.landlord.deposit.claim-notice-days": S("Number of days for a Florida landlord to send written deposit-claim notice", "quantity", ["rent"], "lease", FLSTAT, unit="day"),
    f"{FL}.landlord.deposit.tenant-objection-days": S("Number of days for a Florida tenant to object in writing to a deposit claim", "quantity", ["rent"], "lease", FLSTAT, unit="day"),
    f"{FL}.fpl.deposit-months": S("Number of months of deposit Florida Power & Light may require", "quantity", ["utilities"], "power", FPL, unit="month"),
    f"{FL}.fpl.deposit-refund-months": S("Number of months after which Florida Power & Light refunds a qualifying deposit", "quantity", ["utilities"], "power", FPL, unit="month"),
    f"{FL}.liheap.household-status-requirement": S("Household status requirement for Miami-Dade LIHEAP assistance", "text", ["utilities"], "power", LIHEAP),
    f"{FL}.local-id.restriction": S("Florida restriction or eligibility rule for a local identification card", "text", ["license"], "flhsmv", DHSMV),
    f"{FL}.business-tax.due-date": S("Florida local business tax receipt due date", "date", ["taxes"], "business_tax", "Miami-Dade Tax Collector"),
    f"{FL}.business-tax.october-penalty": S("Florida local business tax receipt October late penalty", "quantity", ["taxes"], "business_tax", "Miami-Dade Tax Collector", unit="percent"),
    f"{FL}.business-tax.exemption-65-disabled": S("Whether a qualifying person age 65 or disabled may claim a local business tax payment exemption", "flag", ["taxes"], "business_tax", "Miami-Dade Tax Collector"),
    f"{FL}.flhsmv.address-proofs-count": S("How many proofs of Florida residential address FLHSMV requires for a license or ID", "quantity", ["license"], "flhsmv", DHSMV, unit="document"),
    f"{FL}.flhsmv.document-list": S("FLHSMV's list of accepted documents for identity, lawful presence, Social Security number, and address", "text", ["license"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.exams-english-only": S("Whether every Florida driver license knowledge and skills exam is given in English only, with no interpreter or translation", "flag", ["license", "driving"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.class-e-exam-languages": S("Languages the FLHSMV Class E knowledge exam page says the exam is offered in", "text", ["license", "driving"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.no-interpreter": S("Whether interpreters or translation are allowed at Florida driver license knowledge or skills exams", "flag", ["license", "driving"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.driver-handbook.url": S("Link to FLHSMV's official English driver handbook", "code", ["license", "driving"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.fee.class-e-original": S("Original Florida Class E driver-license fee", "money", ["license"], "flhsmv", DHSMV, unit="USD"),
    f"{FL}.flhsmv.fee.id-card-original": S("Original Florida identification-card fee", "money", ["license"], "flhsmv", DHSMV, unit="USD"),
    f"{FL}.flhsmv.fee.tax-collector-service-fee": S("Additional Florida tax-collector office service fee for a driver license or ID credential", "money", ["license", "money"], "flhsmv", DHSMV, unit="USD", desk=f"{MD}.tax-collector"),
    f"{FL}.flhsmv.f1-documents": S("Extra documents an F-1 student brings to FLHSMV (I-20, I-94, and school letter rules)", "text", ["license", "immigration"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.foreign-license": S("Whether and for how long a foreign driver license can be used in Florida, and when a new resident must get a Florida one", "text", ["license"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.lawful-presence": S("Rule that a Florida license or ID requires proof of lawful presence, and which USCIS documents count", "text", ["license", "immigration"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.noncitizen-mailed": S("Rule that a non-citizen's first license or ID may be mailed rather than handed over at the counter", "text", ["license", "immigration"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.noncitizen-max-validity": S("Longest a non-citizen's Florida license or ID can be valid, even if the USCIS document runs longer", "quantity", ["license", "immigration"], "flhsmv", DHSMV, unit="year"),
    f"{FL}.flhsmv.noncitizen-original-document": S("Rule that non-citizens bring original (not copied) immigration documents to FLHSMV", "text", ["license", "immigration"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.ssn-if-issued": S("Rule that the Social Security number is required only if one was issued", "text", ["license"], "flhsmv", DHSMV),
    f"{FL}.flhsmv.student-documents": S("Documents a student brings to FLHSMV as proof of address when living with family or in school housing", "text", ["license"], "flhsmv", DHSMV),
    f"{FL}.hospital.itemized-bill": S("Florida patient's right to an itemized hospital bill, and how to ask for it", "text", [], "medbill", "Florida Statutes / Florida AHCA"),
    f"{FL}.housing.floridahousingsearch": S("Name of Florida's official affordable-housing listing service, cited as the source of the building list", "code", ["rent"], "buildings", "Florida Housing Finance Corporation"),
    f"{FL}.insurance.required": S("Rule that every registered car in Florida must carry insurance continuously", "text", ["license"], "insurance", DHSMV),
    f"{FL}.insurance.suspension": S("What happens to license and registration if Florida car insurance lapses", "text", ["license"], "insurance", DHSMV),
    f"{FL}.medicaid.access-applications": S("How Floridians apply for Medicaid and related benefits (ACCESS Florida, through DCF)", "text", [], "coverage", "Florida DCF (ACCESS Florida)"),
    f"{FL}.notary.no-immigration-advice": S("Florida rule that a notary public may not give immigration advice or call themselves a notario", "text", ["immigration", "legal-aid"], "helper", "Florida Statutes / Florida Department of State"),
    f"{FL}.school-bus-camera.law": S("Florida law allowing school-bus stop-arm cameras, and the civil penalty process", "text", ["schools"], "buscam", "Florida Statutes"),
    f"{FL}.school.immunization-form": S("Name and number of the Florida school-entry immunization certificate form", "code", ["schools"], "schoolenr", "Florida Department of Health"),
    f"{FL}.school.immunization-transfer": S("How foreign or out-of-state vaccine records are transferred onto the Florida form (who can do it, free options)", "text", ["schools"], "schoolenr", "Florida Department of Health"),
    f"{FL}.toll.agencies": S("The toll agencies that bill drivers in South Florida (names)", "codes", ["tolls"], "toll_rules", "Florida DOT / Florida's Turnpike / GMX"),
    f"{FL}.toll.cashless": S("Rule that Florida toll roads are cashless: SunPass or a toll-by-plate invoice", "text", ["tolls"], "toll_rules", "Florida's Turnpike Enterprise (SunPass)"),
    f"{FL}.toll.express-lanes": S("Rule that I-95 express lanes are dynamically priced and need a transponder", "text", ["tolls"], "toll_rules", "Florida DOT"),
    f"{FL}.toll.invoice-sequence": S("Order of toll-by-plate invoices and what happens when one is not paid (fees, registration hold)", "text", ["tolls"], "toll_rules", "Florida's Turnpike Enterprise (SunPass)"),
    f"{FL}.toll.rental-car-programs": S("How rental-car toll programs work in Florida and what they charge on top of tolls", "text", ["tolls"], "toll_rules", "Florida's Turnpike Enterprise / rental companies"),
    f"{FL}.toll.sunpass-plate-link": S("Rule that a SunPass account must list the plate or the transponder, or tolls go to the plate owner by invoice", "text", ["tolls"], "toll_rules", "Florida's Turnpike Enterprise (SunPass)"),
    f"{FL}.towing.statute": S("The Florida statute that governs towing from private property (citation)", "code", [], "tow", "Florida Statutes"),
})

F.update({
    # ---- Federal (us)
    f"{US}.alcohol.minimum-age": S("Minimum legal age to buy or drink alcohol", "quantity", [], "country", "U.S. federal law / Florida Statutes", unit="year"),
    f"{US}.bank.account-owner": S("Rule that a bank account belongs to the person named on it, so no one else should open or hold one for you", "text", [], "bank", "CFPB / FDIC"),
    f"{US}.bank.passport-foreign-address": S("Whether a bank can open an account with a foreign passport and a foreign or new address (customer identification rule)", "text", [], "bank", "FDIC / FinCEN (customer identification program)"),
    f"{FL}.minimum-wage.hourly": S("Florida's hourly minimum wage now in force (Florida Constitution, Art. X §24)", "money", [], "bls", "Florida Constitution / FL Department of Commerce", unit="USD/hour"),
    f"{US}.bls.oews-miami-metro": S("Median yearly pay for the household's occupation in the Miami metro (BLS OEWS)", "money", [], "bls", "U.S. Bureau of Labor Statistics (OEWS)", unit="USD"),
    f"{US}.cdc.heat-illness-signs": S("Warning signs of heat exhaustion and heat stroke, and when to call 911", "text", [], "heat", "CDC"),
    f"{US}.census.county-subdivision": L("The Census county subdivision the pin is in", "code", ["municipality"], "census", "U.S. Census Bureau", "For a pin, which Census county subdivision contains it (official name)?", EP["census"]),
    f"{US}.check-cashing.fees": S("That check-cashing stores charge a fee on each check, and how that fee is set", "text", [], "bank", "CFPB / Florida Office of Financial Regulation"),
    f"{US}.credit.cosigner-liability": S("Rule that a cosigner owes the whole debt if the borrower does not pay", "text", [], "bank", "CFPB / FTC"),
    f"{US}.credit.no-file": S("What having no U.S. credit file means for renting and borrowing", "text", [], "bank", "CFPB"),
    f"{US}.credit.no-file-guarantor": S("How renters with no credit file use a guarantor or a larger deposit instead", "text", ["rent"], "bank", "CFPB"),
    f"{US}.credit.secured-card": S("How a secured credit card works to start a credit history", "text", [], "bank", "CFPB"),
    f"{US}.education.credential-evaluation": S("How foreign diplomas and degrees are evaluated in the U.S. (credential evaluation services)", "text", [], "cred", "U.S. Department of Education"),
    f"{US}.energy.cooling-tips": S("Official tips to keep cooling costs down in hot weather", "text", [], "heat", "U.S. Department of Energy (Energy Saver)"),
    f"{US}.eoir.recognized-organizations": S("That the Justice Department (EOIR) keeps the roster of recognized organizations and accredited representatives allowed to give immigration legal help", "text", ["immigration", "legal-aid"], "helper", "U.S. Department of Justice (EOIR)"),
    f"{US}.f1.full-course-load": S("Rule that an F-1 student must keep a full course load each term", "text", ["immigration"], "f1", SEVP),
    f"{US}.f1.on-campus-hours-limit": S("Weekly limit on on-campus work for an F-1 student while classes are in session", "quantity", ["immigration"], "f1", SEVP, unit="hour per week"),
    f"{US}.f1.sevis-address-deadline": S("How soon an F-1 student must report a new address to the school so SEVIS is updated", "quantity", ["immigration"], "f1", SEVP, unit="day"),
    f"{US}.f1.work-through-dso": S("Rule that an F-1 student checks with the school's DSO before taking any work", "text", ["immigration"], "f1", SEVP),
    f"{US}.medicare.noncitizen.eligible-groups": S("Non-citizen groups eligible for Medicare", "codes", ["immigration"], "country", CMS),
    f"{US}.medicare.noncitizen.existing-enrollee-rule": S("Rule for an existing Medicare enrollee who is not a U.S. citizen", "text", ["immigration"], "country", CMS),
    f"{US}.immigration.f1.fixed-admission.effective": S("Effective date of the F-1 fixed-admission rule", "date", ["immigration"], "f1", "U.S. Department of State / U.S. ICE"),
    f"{US}.immigration.f1.fixed-admission.length": S("Length of the F-1 fixed admission period", "text", ["immigration"], "f1", "U.S. Department of State / U.S. ICE"),
    f"{US}.irs.itin.not-id": S("Identification documents or uses an ITIN does not serve as", "codes", [], "taxes", "IRS"),
    f"{US}.fema.flood-zone": L("The FEMA flood zone for the address pin", "code", ["flood"], "fema", FEMA,
        "For a pin, which FEMA flood zone does the address fall in?", EP["fema"]),
    f"{US}.health.emtala": S("Rule that a hospital emergency room must screen and stabilize anyone, whatever their ability to pay or status (EMTALA)", "text", [], "hospital", "CMS"),
    f"{US}.health.er-vs-clinic-cost": S("That an ER visit usually costs far more than a clinic or urgent-care visit for the same non-emergency problem", "text", [], "hospital", "HHS / HealthCare.gov"),
    f"{US}.health.fqhc-sliding-scale": S("Rule that federally funded community health centers charge on a sliding scale by income, whatever the patient's status", "text", [], "hospital", "HRSA"),
    f"{US}.hhs.45-cfr-92.201.requirement": S("Rule requiring covered health programs that receive federal funding to provide meaningful language access for people with limited English proficiency", "text", ["health", "language"], "hospital", "HHS / eCFR"),
    f"{US}.health.when-to-call-911": S("Signs that mean call 911 instead of going to a clinic (chest pain, trouble breathing, heavy bleeding)", "text", [], "hospital", "HHS / NIH MedlinePlus"),
    f"{US}.hud.income-limits-purpose": S("What HUD income limits are for (program eligibility bands by household size), and that they are not a rent quote", "text", ["rent"], "hud", "U.S. HUD"),
    f"{US}.immigration.who-may-advise": S("Rule that only a lawyer or a DOJ-accredited representative at a recognized organization may give immigration legal advice", "text", ["immigration", "legal-aid"], "status", "U.S. Department of Justice (EOIR) / USCIS"),
    f"{US}.irs.filing-deadline": S("The yearly federal income-tax filing deadline (day of the year)", "date", [], "taxes", "IRS"),
    f"{US}.irs.itin": S("What an ITIN is and who applies for one", "text", [], "taxes", "IRS"),
    f"{US}.irs.itin-not-work-permit": S("Rule that an ITIN does not give permission to work", "text", ["immigration"], "taxes", "IRS"),
    f"{US}.irs.late-penalties": S("That filing or paying federal taxes late brings penalties and interest", "text", [], "taxes", "IRS"),
    f"{US}.irs.vita": S("The IRS VITA free tax-preparation program and who qualifies", "text", [], "taxes", "IRS"),
    f"{US}.irs.who-must-file": S("Who must file a federal tax return, whatever their immigration status", "text", [], "taxes", "IRS"),
    f"{US}.labor.tipped-wage": S("Rule that tipped workers can be paid a lower cash wage, so tips are part of their pay", "text", [], "pay", "U.S. Department of Labor / Florida minimum-wage notice"),
    f"{US}.lease.income-multiple": S("Common landlord rule of how many times the monthly rent a renter's monthly income must be", "quantity", ["rent"], "lease", "to be identified by Research (landlord practice, fair-housing guidance)", unit="times monthly rent", ftype="practice"),
    f"{US}.mobile.prepaid-without-ssn": S("That prepaid phone plans can be bought without a Social Security number or credit check", "text", [], "country", "FCC / carrier terms"),
    f"{US}.nhtsa.hot-car": S("Hot-car danger: never leave a child or pet in a parked car, even briefly", "text", [], "heat", "NHTSA"),
    f"{US}.rights.free-to-go": S("Right to ask a police officer whether you are free to go", "text", ["legal-aid"], "rights", "U.S. constitutional rights guidance (DOJ / ACLU)"),
    f"{US}.rights.search-consent": S("Right to refuse consent to a search, without resisting", "text", ["legal-aid"], "rights", "U.S. constitutional rights guidance (DOJ / ACLU)"),
    f"{US}.rights.silence-and-lawyer": S("Right to stay silent and to ask for a lawyer", "text", ["legal-aid"], "rights", "U.S. constitutional rights guidance (DOJ / ACLU)"),
    f"{US}.school.immunization-state-law": S("That school vaccine requirements are set by each state, with its own exemption rules", "text", ["schools"], "country", "CDC"),
    f"{US}.status.asylum-applicant": S("Plain meaning of 'asylum applicant' as USCIS uses it", "text", ["immigration"], "status", "USCIS (glossary)"),
    f"{US}.status.ead": S("Plain meaning of an Employment Authorization Document (EAD, work permit)", "text", ["immigration"], "status", "USCIS"),
    f"{US}.status.green-card": S("Plain meaning of lawful permanent resident (green card)", "text", ["immigration"], "status", "USCIS"),
    f"{US}.status.parole": S("Plain meaning of humanitarian parole as USCIS uses it", "text", ["immigration"], "status", "USCIS"),
    f"{US}.status.tps": S("Plain meaning of Temporary Protected Status (TPS)", "text", ["immigration", "tps"], "status", "USCIS"),
    f"{US}.status.visa-vs-status": S("Difference between a visa (permission to arrive) and a status (permission to stay)", "text", ["immigration"], "status", "U.S. Department of State / USCIS"),
    f"{US}.tipping.service-charge": S("That some bills already include a service charge or gratuity, so check before tipping", "text", [], "country", "to be identified by Research (consumer guidance)", ftype="practice"),
    f"{US}.tipping.sit-down-range": S("Usual tip range at a sit-down restaurant, as a percent of the bill", "text", [], "country", "to be identified by Research (etiquette guidance)", ftype="practice"),
    f"{US}.voting.citizens-only": S("Rule that only U.S. citizens may register and vote in federal and Florida elections", "text", ["voting", "immigration"], "citizen", "U.S. Election Assistance Commission / Florida Division of Elections"),
    f"{US}.voting.noncitizen-consequence": S("Consequences for a non-citizen who registers or votes (crime, removal, bar to citizenship)", "text", ["voting", "immigration"], "citizen", "USCIS / U.S. Department of Justice"),
    # desk-namespaced (federal), not contact fields
    f"{US}.911.any-phone": S("Rule that 911 works from any phone, even without service or credit", "text", ["desk"], "rights", "FCC"),
    f"{US}.211.food-referrals": S("That 211 refers callers to food pantries and meal programs", "text", ["desk"], "help", "211 Miami / United Way"),
    f"{US}.cbp.i94-online": S("That the I-94 arrival record is looked up and printed on the CBP website", "text", ["immigration"], "paper", "U.S. CBP"),
    f"{US}.cfpb.remittance-cancel-window": S("How long after paying a sender can cancel an international money transfer for a full refund", "quantity", [], "remit", "CFPB (Remittance Transfer Rule)", unit="minute"),
    f"{US}.cfpb.remittance-disclosure": S("Rule that a money-transfer company must give a receipt with fees, exchange rate, and amount received", "text", [], "remit", "CFPB (Remittance Transfer Rule)"),
    f"{US}.ftc.government-impostor": S("Signs of a government-impostor call or letter (threats, demands for gift cards or wires)", "text", [], "letter", "FTC"),
    f"{US}.ftc.payment-red-flags": S("Payment methods scammers demand (gift cards, wires, crypto, payment apps) as red flags", "text", [], "letter", "FTC"),
    f"{US}.ftc.gift-card-payment-scam": S("FTC rule that a request to pay with a gift card is a scam", "text", ["scams"], "letter", "FTC"),
    f"{US}.ftc.rental-scam-signs": S("Signs of a rental-listing scam (money before seeing the place, owner abroad, wire)", "text", ["rent"], "lease", "FTC"),
    f"{US}.ftc.rental-scam-signs.es": S("Spanish-language signs of a rental-listing scam (money before seeing the place, owner abroad, wire)", "text", ["rent"], "lease", "FTC"),
    f"{US}.ftc.toll-text-scam": S("Signs of the unpaid-toll text scam, and where to check a real toll bill", "text", ["tolls"], "letter", "FTC"),
    f"{US}.ssa.ssn-eligibility": S("Who can get a Social Security number (work-authorized non-citizens) and who cannot", "text", ["immigration"], "taxes", "Social Security Administration"),
    f"{US}.ssa.ssn-misuse": S("What to do if someone misuses your Social Security number", "text", [], "taxes", "Social Security Administration / FTC"),
    f"{US}.uscis.address-change-deadline": S("How soon a non-citizen must report a new address to USCIS", "quantity", ["immigration"], "paper", "USCIS", unit="day"),
    f"{US}.uscis.address-change-online": S("That the USCIS address change is filed online", "text", ["immigration"], "paper", "USCIS"),
    f"{US}.uscis.forms-free": S("Rule that USCIS forms are free to download from USCIS", "text", ["immigration"], "helper", "USCIS"),
    f"{US}.uscis.fee-payment-methods": S("USCIS fee-payment methods for online and mailed benefit requests", "text", ["immigration"], "paper", "USCIS"),
    f"{US}.uscis.missed-appointment": S("What to do after missing a USCIS appointment (rescheduling rule)", "text", ["immigration"], "paper", "USCIS"),
    f"{US}.uscis.notario-scam": S("USCIS warning about notario and immigration-consultant scams", "text", ["immigration", "legal-aid"], "helper", "USCIS"),
    f"{US}.uscis.notices-by-mail": S("That USCIS sends notices by mail to the address on file, so it must be current", "text", ["immigration"], "paper", "USCIS"),
    f"{US}.uscis.role": S("What USCIS does (benefits and applications), as distinct from CBP and ICE", "text", ["immigration"], "status", "USCIS"),
})

# Verified-only status dates (Firstmate hold). The date itself is never written here.
VO = {
    f"{US}.immigration.tps.haiti.end-date": dict(need="The date the Haiti TPS designation ended, and whether its work permits are still valid, as USCIS publishes it", topics=["immigration", "tps"], pub="USCIS / Federal Register"),
    f"{US}.immigration.tps.venezuela.doc-validity": dict(need="The date through which the court-protected Venezuela TPS documents (EAD, I-797, I-94) stay valid, and which documents it covers", topics=["immigration", "tps"], pub="USCIS / Federal Register"),
    f"{US}.medicaid.hr1.noncitizen-eligibility.effective": dict(need="The date federal Medicaid/CHIP matching funds end for some non-citizen groups (H.R.1)", topics=["immigration", "health"], pub="Public law text / CMS"),
}

DESK_HINTS = {
    "us-fl-miamidade.311": "311", "us-fl-miamidade.property-appraiser": "parcel", "us-fl-miamidade.tax-collector": "taxcoll",
    "us-fl-miamidade.gmx": "gmx", "us-fl.sunpass": "toll_rules", "us-fl-miamidade.elections": "vote",
    "us-fl-miamidade.libraries": "places", "us-fl-miamidade.water-sewer": "water", "us-fl-miamidade.transit": "transit", "us-fl.sfrta": "sfrta",
    "us-fl-miamidade.m-dcps": "mdcps", "us-fl-miamidade.school-bus-camera": "buscam", "us-fl-miamidade.housing": "income_county",
    "us-fl-miamidade.mia-information": "mia", "us-fl-miamidade.mia-rental-car-center": "mia",
    "us-fl-miamidade.internet-providers": "broadband", "us-fl-miamidade.grocery-store": "grocery",
    "us.accredited-legal-help": "helper", "us-fl-miamidade.immigration-legal-aid": "helper", "us.211": "help",
    "us-fl-miamidade.homeless-trust": "help", "us.community-health-center": "hospital", "us-fl-miamidade.jackson": "medbill",
    "us.cfpb": "remit", "us.ftc": "letter", "us.irs": "taxes", "us.ssa": "taxes", "us.uscis": "paper", "us.cbp": "paper",
    "us.school-dso": "f1", "us-fl.flhsmv": "flhsmv", "us-fl.dcf-access": "coverage", "us.bank-branch": "bank",
    "us-fl-miamidade.consumer-protection": "tow", "us.911": "rights",
}
DESK_FIELD_NEED = {
    "name": "Official name of {d}, exactly as the agency writes it",
    "phone": "Public phone number for {d}",
    "url": "Official web address for {d}",
    "address": "Street address of {d}",
    "hours": "Opening or phone hours of {d}",
    "languages": "Languages {d} answers in (phone line or counter)",
}


def load(path):
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def topic_vocab():
    """research/topics.yaml is the authority when present; otherwise the seed list."""
    if not TOPICS_FILE.exists():
        return set(SEED_TOPICS)
    doc = load(TOPICS_FILE)
    items = doc.get("topics", []) if isinstance(doc, dict) else doc
    vocab = set()
    for it in items or []:
        if isinstance(it, str):
            vocab.add(it)
        elif isinstance(it, dict):
            for k in ("id", "tag", "name"):
                if isinstance(it.get(k), str):
                    vocab.add(it[k])
                    break
    return vocab


def strings(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, dict):
        for v in obj.values():
            yield from strings(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from strings(v)


def lower_first(s):
    return s[0].lower() + s[1:] if s else s


def fact_topic(topics):
    """The ledger topic is derived only from its requested topic tags."""
    return "immigration" if {"immigration", "tps"} & set(topics or []) else "general"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--check-fresh", action="store_true")
    ap.add_argument("--output", type=Path, default=OUT,
                    help="generated path (used by CI freshness checks)")
    args = ap.parse_args(argv)

    vocab = topic_vocab()
    tr_path = CONTENT / "topics-requested.yaml"
    pending_tags = {i.get("tag") for i in ((load(tr_path) or {}).get("requested") or []) if isinstance(i, dict)} if tr_path.exists() else set()
    desks = {d["id"]: d for d in (load(CONTENT / "desks.yaml").get("desks") or [])}
    cards = {}
    for p in sorted(glob.glob(str(CONTENT / "cards" / "*.yaml"))):
        c = load(p)
        if isinstance(c, dict) and c.get("id"):
            cards[c["id"]] = c
    lenses = {}
    for p in sorted(glob.glob(str(CONTENT / "lenses" / "*.yaml"))):
        lz = load(p)
        if isinstance(lz, dict) and lz.get("id"):
            lenses[lz["id"]] = lz

    direct = collections.defaultdict(list)  # fid -> cards citing it directly, in card order
    vo_ids = set()
    for cid, c in cards.items():
        refs = list(c.get("fact_refs") or [])
        vo = list(c.get("verified_only_refs") or [])
        vo_ids.update(vo)
        refs += vo
        for key in ("title", "summary", "body"):
            for s in strings(c.get(key)):
                refs += PLACEHOLDER_RE.findall(s)
        for para in c.get("paragraph_facts") or []:
            refs += list(para or [])
        for f in refs:
            if cid not in direct[f]:
                direct[f].append(cid)
    lens_users = collections.defaultdict(list)
    for lid, lz in lenses.items():
        refs = list(lz.get("fact_refs") or []) + [x for s in strings(lz) for x in PLACEHOLDER_RE.findall(s)]
        for f in refs:
            if lid not in lens_users[f]:
                lens_users[f].append(lid)

    enders, actors = collections.defaultdict(list), collections.defaultdict(list)
    for cid, c in cards.items():
        if c.get("desk"):
            enders[c["desk"]].append(cid)
        for a in c.get("actions") or []:
            ad = isinstance(a, dict) and (a.get("desk_id") or (a.get("target") or {}).get("desk_id"))
            if ad and cid not in actors[ad]:
                actors[ad].append(cid)
    desk_refs = {f: did for did, d in desks.items() for f in (d.get("fact_refs") or [])}

    ids = set(direct) | set(desk_refs)

    def ns_desk_of(fid):
        best = None
        for did in desks:
            if fid.startswith(did + ".") and (best is None or len(did) > len(best)):
                best = did
        return best

    entries, fallback, problems = [], [], []
    for fid in sorted(ids):
        pack = fid.split(".", 1)[0]
        ns_desk = ns_desk_of(fid)
        field = fid.rsplit(".", 1)[1]
        is_contact = bool(ns_desk) and fid == f"{ns_desk}.{field}" and field in DESK_FIELDS
        users = list(direct.get(fid, []))
        cards_list = list(users)
        if is_contact:
            for cid in enders.get(ns_desk, []) + actors.get(ns_desk, []):
                if cid not in cards_list:
                    cards_list.append(cid)
        first = (users or (enders.get(ns_desk, []) if ns_desk else []) or cards_list or [None])[0]
        if first is None:
            problems.append(f"{fid}: no card shows it")
            first = sorted(cards)[0]
        if ns_desk:
            desk = ns_desk
        else:
            cnt = collections.Counter(cards[c].get("desk") for c in users if cards[c].get("desk"))
            desk = cnt.most_common(1)[0][0] if cnt else None
            if desk is None:
                problems.append(f"{fid}: no owning desk")
        used_by = [f"card:{c}" for c in users] + [f"lens:{lid}" for lid in lens_users.get(fid, [])]
        if fid in desk_refs:
            used_by.append(f"desk:{desk_refs[fid]}")
        if not used_by and ns_desk:
            used_by = [f"desk:{ns_desk}"]  # extra contact field the desk owns but desks.yaml does not list yet

        note, verified_only, endpoint, unit, q = None, False, None, None, None
        if fid in vo_ids or fid in VO:
            spec = VO.get(fid)
            if spec is None:
                fallback.append(fid)
                spec = dict(need=f"Status date named by {fid}", topics=["immigration"], pub="USCIS / Federal Register / CMS / FL AHCA")
            need, vt, kind, topics, pub, ftype = spec["need"], "date", "static", spec["topics"], spec["pub"], "official"
            hint, pref = VO_HINT, None
            verified_only = True
            note = (f"Status date under the Firstmate hold: {VO_HINT}. Cards carry it only in verified_only_refs; "
                    "the app shows it only when the ledger status is verified.")
            q = f"What exact date does the primary source give for: {lower_first(need)}? Quote the notice and link the primary page."
        elif is_contact:
            d = desks[ns_desk]
            dname = (d.get("name") or {}).get("en", ns_desk)
            kind = d.get("contact_kind", "static")
            vt = DESK_FIELD_TYPES[field]
            need = DESK_FIELD_NEED[field].format(d=dname if kind == "static" else f"{dname} (the one nearest the pin)")
            topics = list(d.get("topics") or []) + ["desk"]
            hk = DESK_HINTS.get(ns_desk)
            if hk:
                hint, pref = H[hk][0] + f"; the {field} itself comes from the desk's own official page", H[hk][1]
            else:
                hint, pref = f"not named in the plans; the desk's own official page ({dname})", None
            pub = dname
            ftype = "adapter-table" if kind == "lookup" else "official"
            q = (f"For a pin, which one is nearest ({dname}), and what is its {field}?" if kind == "lookup"
                 else f"What is the {field} of {dname}, as the agency publishes it on its own page?")
        elif fid in F:
            s = F[fid]
            need, vt, kind = s["need"], s["vt"], s["kind"]
            topics = list(s["topics"])
            hint, pref = H[s["hint"]]
            pub = s["pub"]
            ftype = s.get("ftype", "adapter-table" if kind == "lookup" else "official")
            unit, note = s.get("unit"), s.get("note")
            endpoint = s.get("endpoint") if kind == "lookup" else None
            q = s.get("q") or (f"{JURIS[pack]}: {lower_first(need)}. What does the primary source ({pub}) say, "
                               "in its own words, and on which page?")
        else:  # fallback: listed on stdout so the table gets fixed
            fallback.append(fid)
            words = field.replace("-", " ")
            need = f"{words} ({fid.split('.')[1]}), {JURIS[pack]}"
            vt, kind, topics, pub, ftype = "text", "static", [], "to be identified by Research", "official"
            hint, pref = "not named in the plans; Research to find the primary source", None
            q = f"What is the {words} for {JURIS[pack]}, per the primary source?"

        if fid in F and F[fid].get("desk"):
            # table override: the desk the ledger fact names (e.g. the fee is charged at the county
            # Tax Collector, not by FLHSMV, although the id sits in the FLHSMV namespace)
            desk = F[fid]["desk"]
        if ".groceries." in fid:
            note = GROCERY_NOTE
        # seed/topics.yaml tags only; a verified-only benefits date may also carry the benefits tag
        # ("health") while it is pending in content/topics-requested.yaml.
        allowed = vocab | (BENEFITS_TAGS & pending_tags if verified_only else set())
        topics = [t for t in dict.fromkeys(topics) if t in allowed]
        if vt not in VALUE_TYPES:
            problems.append(f"{fid}: bad value_type {vt}")
        if vt in ("money", "quantity") and not unit:
            problems.append(f"{fid}: {vt} without unit")
        if is_contact:
            topic = "immigration" if desks[ns_desk].get("immigration") else "general"
        else:
            topic = fact_topic(topics)

        e = {"id": fid, "card": first, "cards": cards_list, "need": need, "hint": hint,
             "kind": kind, "value_type": vt}
        if unit:
            e["unit"] = unit
        e.update({"topics": topics, "topic": topic, "desk": desk})
        if kind == "lookup" and q:
            e["question"] = q
        if kind == "lookup" and endpoint:
            e["endpoint"] = endpoint
        e.update({"fact_type": ftype, "status": "requested", "used_by": used_by, "plan_text": None})
        if pref and pref[0] in PLAN_REF_PLANS:
            e["plan_ref"] = {"plan": pref[0], "section": pref[1]}
            e["content_added_reason"] = "plan_text left empty on purpose: plan values are never copied here; see hint and plan_ref"
        else:
            who = f"desk {desk}" if is_contact else f"card {first}"
            e["content_added_reason"] = f"no plan_text copied (values stay out of this file); requested because {who} needs it"
        e["source"] = {"publisher": pub, "url": None}
        if verified_only:
            e["verified_only"] = True
        if note:
            e["note"] = note
        entries.append(e)

    body = yaml.safe_dump({"requested": entries}, sort_keys=False, allow_unicode=True, width=1000)
    generated = HEADER + body
    if args.check_fresh:
        target = args.output
        if not target.exists() or target.read_text(encoding="utf-8") != generated:
            print(f"STALE: {target}")
            return 1
    elif not args.check:
        args.output.write_text(generated, encoding="utf-8")

    c_kind = collections.Counter(e["kind"] for e in entries)
    c_vt = collections.Counter(e["value_type"] for e in entries)
    contact = [e for e in entries if ns_desk_of(e["id"]) and e["id"] == f"{ns_desk_of(e['id'])}.{e['id'].rsplit('.', 1)[1]}"
               and e["id"].rsplit(".", 1)[1] in DESK_FIELDS]
    extra = [e["id"] for e in contact if e["id"] not in desk_refs and not direct.get(e["id"])]
    print(f"entries={len(entries)} kind={dict(c_kind)} desk_contact_facts={len(contact)} (not in desks.yaml fact_refs: {len(extra)})")
    print(f"value_type={dict(sorted(c_vt.items()))}")
    print(f"topic_field={dict(collections.Counter(e['topic'] for e in entries))} no_topic_tags={sum(1 for e in entries if not e['topics'])}")
    print(f"verified_only={sorted(e['id'] for e in entries if e.get('verified_only'))}")
    print(f"fallback={fallback}")
    print(f"problems={problems[:20]}")
    print(f"table_ids_not_referenced={sorted(set(F) - ids)}")
    print(f"lens_only_ids={sorted(set(lens_users) - ids)}")
    print(f"wrote={'no (--check/--check-fresh)' if (args.check or args.check_fresh) else args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
